[jobs.webserver]
command = ["cargo", "run", "--bin", "server"]
need_stdout = true
background = false
on_change_strategy = "kill_then_restart"
kill = ["kill", "-s", "INT"]
env = { REDIS_URL = "redis://localhost:6379", RUST_LOG = "debug" }
